export const dummyServices = [
  {
    id: "1",
    title: "Professional Bookkeeping Services",
    description: "I will do bookkeeping using quickbooks online, xero, excel",
    freelancerName: "Budi Santoso",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=BudiSantoso",
    freelancerLevel: "Level 2",
    rating: 4.8,
    reviewCount: 759,
    priceFrom: 650000,
    imageUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=500&h=300&fit=crop",
    tags: ["Quickbooks", "Xero", "Excel"],
    serviceType: "bookkeeper",
    isVerified: true,
  },
  {
    id: "2",
    title: "Chartered Accountant Services",
    description: "I will do accounting and audit as a senior auditor",
    freelancerName: "Dewi Lestari",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=DewiLestari",
    freelancerLevel: "Level 2",
    rating: 5.0,
    reviewCount: 33,
    priceFrom: 1200000,
    imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=500&h=300&fit=crop",
    tags: ["Audit", "Financial Statements", "CPA"],
    serviceType: "auditor",
    isVerified: false,
  },
  {
    id: "3",
    title: "Expert CPA Services",
    description: "I will build a comprehensive profit loss, financial statement, CPA letter",
    freelancerName: "Ahmad Hidayat",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AhmadHidayat",
    freelancerLevel: "Top Rated",
    rating: 4.9,
    reviewCount: 476,
    priceFrom: 2500000,
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&h=300&fit=crop",
    tags: ["CPA", "Financial Reporting", "Tax"],
    serviceType: "financial_accountant",
    isVerified: true,
  },
  {
    id: "4",
    title: "Real Estate Bookkeeping",
    description: "I will do real estate, airbnb, rentals and property management bookkeeping",
    freelancerName: "Siti Nurhaliza",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=SitiNurhaliza",
    freelancerLevel: "Level 2",
    rating: 5.0,
    reviewCount: 19,
    priceFrom: 500000,
    imageUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=500&h=300&fit=crop",
    tags: ["Real Estate", "Airbnb", "QuickBooks"],
    serviceType: "bookkeeper",
    isVerified: false,
  },
  {
    id: "5",
    title: "Tax Preparation Services",
    description: "I will prepare your tax returns with maximum deductions and accuracy",
    freelancerName: "Andi Wijaya",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=AndiWijaya",
    freelancerLevel: "Top Rated",
    rating: 4.9,
    reviewCount: 892,
    priceFrom: 1800000,
    imageUrl: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=500&h=300&fit=crop",
    tags: ["Tax", "Pajak", "Deductions"],
    serviceType: "tax_accountant",
    isVerified: true,
  },
  {
    id: "6",
    title: "Financial Analysis & Reporting",
    description: "I will provide comprehensive financial analysis and custom reports for your business",
    freelancerName: "Rina Kusuma",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=RinaKusuma",
    freelancerLevel: "Level 2",
    rating: 4.7,
    reviewCount: 234,
    priceFrom: 1500000,
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&h=300&fit=crop",
    tags: ["Financial Analysis", "Reporting", "Forecasting"],
    serviceType: "financial_analyst",
    isVerified: true,
  },
  {
    id: "7",
    title: "Payroll Processing Expert",
    description: "I will handle complete payroll processing, tax calculations, and compliance",
    freelancerName: "Hendra Gunawan",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=HendraGunawan",
    freelancerLevel: "Level 2",
    rating: 4.8,
    reviewCount: 156,
    priceFrom: 800000,
    imageUrl: "https://images.unsplash.com/photo-1590650153855-d9e808231d41?w=500&h=300&fit=crop",
    tags: ["Payroll", "ADP", "Gusto"],
    serviceType: "payroll_specialist",
    isVerified: false,
  },
  {
    id: "8",
    title: "Management Accounting Services",
    description: "I will provide management accounting, budgeting, and cost analysis for your business",
    freelancerName: "Lina Marlina",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=LinaMarlina",
    freelancerLevel: "Top Rated",
    rating: 5.0,
    reviewCount: 421,
    priceFrom: 3200000,
    imageUrl: "https://images.unsplash.com/photo-1664575602276-acd073f104c1?w=500&h=300&fit=crop",
    tags: ["Management Accounting", "Budgeting", "KPIs"],
    serviceType: "management_accountant",
    isVerified: true,
  },
];

export const categoryStats = {
  totalServices: 18000,
  categories: [
    { name: "Bookkeeping", count: 5200 },
    { name: "Tax Accounting", count: 3800 },
    { name: "Financial Analysis", count: 2900 },
    { name: "Auditing", count: 2100 },
    { name: "Payroll", count: 1800 },
    { name: "Management Accounting", count: 1200 },
    { name: "Other", count: 1000 },
  ],
};
