export const dummyServices = [
  {
    id: "1",
    title: "Professional Bookkeeping Services",
    description: "I will do bookkeeping using quickbooks online, xero, excel",
    freelancerName: "Sarah Johnson",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    freelancerLevel: "Level 2",
    rating: 4.8,
    reviewCount: 759,
    priceFrom: 30,
    imageUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=500&h=300&fit=crop",
    tags: ["Quickbooks", "Xero", "Excel"],
    serviceType: "bookkeeper",
  },
  {
    id: "2",
    title: "Chartered Accountant Services",
    description: "I will do accounting and audit as a senior auditor",
    freelancerName: "Kaffia Imran",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kaffia",
    freelancerLevel: "Level 2",
    rating: 5.0,
    reviewCount: 33,
    priceFrom: 50,
    imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=500&h=300&fit=crop",
    tags: ["Audit", "Financial Statements", "CPA"],
    serviceType: "auditor",
  },
  {
    id: "3",
    title: "US CPA Services",
    description: "I will build a US CPA profit loss, financial statement, CPA letter",
    freelancerName: "Ahps Cpas",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ahps",
    freelancerLevel: "Top Rated",
    rating: 4.9,
    reviewCount: 476,
    priceFrom: 90,
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&h=300&fit=crop",
    tags: ["CPA", "Financial Reporting", "US Tax"],
    serviceType: "financial_accountant",
  },
  {
    id: "4",
    title: "Real Estate Bookkeeping",
    description: "I will do real estate, airbnb, rentals and property management bookkeeping",
    freelancerName: "Minahil K",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Minahil",
    freelancerLevel: "Level 2",
    rating: 5.0,
    reviewCount: 19,
    priceFrom: 10,
    imageUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=500&h=300&fit=crop",
    tags: ["Real Estate", "Airbnb", "QuickBooks"],
    serviceType: "bookkeeper",
  },
  {
    id: "5",
    title: "Tax Preparation Services",
    description: "I will prepare your tax returns with maximum deductions and accuracy",
    freelancerName: "David Chen",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    freelancerLevel: "Top Rated",
    rating: 4.9,
    reviewCount: 892,
    priceFrom: 75,
    imageUrl: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=500&h=300&fit=crop",
    tags: ["Tax", "IRS", "Deductions"],
    serviceType: "tax_accountant",
  },
  {
    id: "6",
    title: "Financial Analysis & Reporting",
    description: "I will provide comprehensive financial analysis and custom reports for your business",
    freelancerName: "Emily Rodriguez",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
    freelancerLevel: "Level 2",
    rating: 4.7,
    reviewCount: 234,
    priceFrom: 85,
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&h=300&fit=crop",
    tags: ["Financial Analysis", "Reporting", "Forecasting"],
    serviceType: "financial_analyst",
  },
  {
    id: "7",
    title: "Payroll Processing Expert",
    description: "I will handle complete payroll processing, tax calculations, and compliance",
    freelancerName: "Michael Brown",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    freelancerLevel: "Level 2",
    rating: 4.8,
    reviewCount: 156,
    priceFrom: 45,
    imageUrl: "https://images.unsplash.com/photo-1590650153855-d9e808231d41?w=500&h=300&fit=crop",
    tags: ["Payroll", "ADP", "Gusto"],
    serviceType: "payroll_specialist",
  },
  {
    id: "8",
    title: "Management Accounting Services",
    description: "I will provide management accounting, budgeting, and cost analysis for your business",
    freelancerName: "Lisa Wang",
    freelancerAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
    freelancerLevel: "Top Rated",
    rating: 5.0,
    reviewCount: 421,
    priceFrom: 95,
    imageUrl: "https://images.unsplash.com/photo-1664575602276-acd073f104c1?w=500&h=300&fit=crop",
    tags: ["Management Accounting", "Budgeting", "KPIs"],
    serviceType: "management_accountant",
  },
];

export const categoryStats = {
  totalServices: 18000,
  categories: [
    { name: "Bookkeeping", count: 5200 },
    { name: "Tax Accounting", count: 3800 },
    { name: "Financial Analysis", count: 2900 },
    { name: "Auditing", count: 2100 },
    { name: "Payroll", count: 1800 },
    { name: "Management Accounting", count: 1200 },
    { name: "Other", count: 1000 },
  ],
};
